name: Deploy Telegram Bot

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */48 * * *'  # Re-start every 48 hours

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          ADMIN_IDS: ${{ secrets.ADMIN_IDS }}
        run: |
          export BOT_TOKEN=$BOT_TOKEN
          export ADMIN_IDS=$ADMIN_IDS
          python bot.py  # Change to your bot script name
          
